## A Notebook for Mathematics, Computer Science and Machine Learning
Diogo PEREIRA MARQUES

-----
# Introduction

The present notebook presents and explains important ideas for Computer Science and Machine learning.

It accompanies this explanation with the **computer programming ** and **mathematical implementation** of these ideas.

-----

# Supported languages

<img src="https://upload.wikimedia.org/wikipedia/commons/f/f8/Python_logo_and_wordmark.svg" alt="drawing" width="200"/> <img src="https://hazelcast.org/wp-content/uploads/2016/04/scala-logo.jpg" alt="drawing" width="200"/>

In [8]:
import numpy as np

<a id='root'></a>
-----

# /

+ Function Definition
+ **Data** [$\rightleftharpoons$](#data)
    + Data Structures [$\rightleftharpoons$](#data_structures)
    + Data Types and Operators [$\rightleftharpoons$](#data_types)
        + Simple
            + Numbers
            + Words
        + Complex
            + Image [$\rightleftharpoons$](#image)
            + Vectors and Matrices
            + Sets and Classes
            + Algebra
                + Functions and Properties [$\rightleftharpoons$](#functions_properties)
            + Time
        + Lexic
        + Data Type Equivalence Operations
+ **Computer Programming Language**
    + Local File System Access
    + Method Definition
        + Remarks
    + Computer Application/Program
        + Application Structure
            + Packages
    + Properties
        + Lazy and Greedy Evaluation
        + Class Hierarchy
        + List Comprehension
        + Curry Functions
        + Indentation sensibility
        + Readability
        + Complexity and Performance
        + Mutability and Immutability
        + Side-effect Operations
        + Substitution Model
        + Evaluation strategies: Call-by-value and Call-by-name
        + Call-by-value and Call-by-reference
        + Conditional expressions
        + Recursion and Tail Recursion
        + Objects
        + Exception Handling
+ **Artificial Intelligence** [$\rightleftharpoons$](#ai)
    + Machine Learning [$\rightleftharpoons$](#machine_learning)
        + Deep Learning [$\rightleftharpoons$](#deep_learning)
            + Neural Networks [$\rightleftharpoons$](#neural_networks)
                + Recurrent Neural Networks
                + Standard Neural Networks
                + Convolutional Neural Networks
            + Supervised Learning [$\rightleftharpoons$](#deep_learning)
            + Binary Classification [$\rightleftharpoons$](#binary_classification)
                + Logistic Regression [$\rightleftharpoons$](#logistic_regression)
                + Cost and Loss Functions [$\rightleftharpoons$](#cost_loss_functions)
                + Gradient Descent [$\rightleftharpoons$](#gradient_descent)
            + Computation Graph [$\rightleftharpoons$](#deep_learning)
            + Logistic Regression and Gradient Descent [$\rightleftharpoons$](#deep_learning)
            + Vectorization [$\rightleftharpoons$](#deep_learning)
+ **Meta**
    + New Markdown Cell
    + Code Block
    + Maths and Latex
    + HTML
    + Kernel Cell

<a id='data'></a>
[/](#root)

-----

# Data

Data can be either **structured** or **unstructured**. Human processors are excellent at extrapolating information from the undestructured sort, mechanic processors from the structured sort. Structured data has a **data type**, and data types are either **simple** or **complex**.

<a id='data_types'></a>
[/ Data](#data)

-----

# Data Types

*Entities* belong to *simple* or *complex* data types. Elements of **NUMBERS** represent entities called *quantities*. Numbers from $\mathbb{R}$ to $\mathbb{C}$ represent **continuous** quantities. All other data types sets represent **discrete** entities: $\mathbb{Z}$, $\mathbb{Q}$, **STRING**, etc.


Only **human processors** can understand continuous quantities, **mecanic processors** can only understand discrete quantities.

<a id='data_type_closure'></a>
[/ Data / Data Types](#data_types)

-----

# Closure

All elements of a given data type $\mathbb{D}$ are **closed under certain operations $\mathbb{O}$**, *i.e.*, each element of $\mathbb{D}$ is equivalent to *n* elements of $\mathbb{D}$, related to one another through some *n*-ary relation/operation $\odot \in \mathbb{O}$. 

Typically $\mathbb{D}$ is refered to both by its' elements and by its' relations $\mathbb{O}$.


<a id='symbol'></a>
[/ Data / Data Types](#data_types)

-----

# Symbolic Representation

Each *data type* has it's own *symbolic representation*, which in turn has it's own *lexic of symbols*.
Symbols can be either **alpha-numerical** (characters) or **numerical** (digits). Sequences of digits are called **numbers**, sequences of characters are called **words**.

<a id='symbol'></a>
[/ Data / Data Types / Symbolic Representation](#symbol)

-----

# Lexic

The lexic is composed of elements of the set **CHARACTERS** and the NULL element $\epsilon$, the *symbol without symbol*.

+ **CHARACTERS** = $\mathbb{UNICODE}$ $\bigcup \{ \epsilon \}$ = { [unicode](https://unicode-table.com/en/) } $\bigcup \{ \epsilon \}$

+ **NUMERICAL_CHARACTERS** = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 }

+ **ALPHA_NUMERICAL_CHARACTERS** = **CHARACTERS** - **NUMERICAL_CHARACTERS**


Note that:

+ Characters **do not** represent data. 1 represents the natural number 1, '1' is the character used to represent the natural number 1. As we see in this example, neither the characters nor the integers are not closed under the operation of **concatenation, +**, whilst the integers are closed under the operation **addition, +**.



<center>**1** = '1' + $\epsilon$</center>

<center>**1 + 1** = '1' + ' ' + '+' + '1' = **2**</center>






In [51]:
a = '1'
b = 1

print(
    a == b
)

False


+ Some characters convey meaning not about the *fact* that the word represents, but meaning about **how to display the word** to the word interpreter. These characters are usually refered to as **white-space** characters.

In [52]:
print("11")
print("1\t1")
print("1\n1")

11
1	1
1
1


-----
Data Types > Simple Data Types

# Boolean Values

**BOOLEAN** = { *true*, *false* }. Elements of BOOLEAN represent the concepts of *true* and *false*. BOOLEAN is closed under:
+ Equality, $=$
+ Inequality, $\neq$
+ Disjunction, $\bigvee$
+ Conjunction, $\bigwedge$
+ Negation, 

BOOLEAN elements are usually equivalent to **expression evaluation**.

-----
Data Types.Simple Data Types.
# Numbers



+ $\mathbb{N}$, **natural** numbers: positive integers

+ $\mathbb{Z}$, **integer** numbers: negative and positive integers and 0

+ $\mathbb{Q}$, **rational** numbers: finite decimal value, or periodic infinite decimal value

+ $\mathbb{R}$, **real** numbers: rational and irrational numbers

+ $\mathbb{C}$, **complex** numbers: real and imaginary numbers

# Rational Numbers, $\mathbb{Q}$ | PY

[operators](https://docs.python.org/2/library/math.html)

-----
Data Types.Complex Data Types.
# String

<a id='image'></a>
[/ Data / Data Types / Complex](#data)

-----

# Image

Images are $m \in \mathbb{M}_{h x l}^3 ([0, 255])$, where $h, l$ are the height and the length of the image, and the $m_{i, j}$ are the Red, Green and Blue values. Typically images are **encoded** to columnar vectors $m \in \mathbb{M}_{h x l x 3} ([0, 255])$

<a id='functions_properties'></a>
[/ Data / Data Types / Algebra / Function](#data)

-----

# Functions and Properties

| | | |
| --- | --- | --- |
| |[convex](http://mathworld.wolfram.com/ConvexFunction.html) | |
| [log](http://mathworld.wolfram.com/Logarithm.html) | yes | | 


-----
Data Types.Complex Data Types.
# Series

[mathematical]()

# Series | PY

Series are **NumPy.Arrays** of arrays, or arrays, although the **first have more operations**.


**Properties**
+ Enumerable



Let:

In [2]:
s1 = np.array([[1,2], [2,3], [3,3]])

s2 = np.array([1, 2, 3])

print(
    "s1:\n" + str(s1)
    
    + "\n\ns2:\n" + str(s2)
)

NameError: name 'np' is not defined

-----
Series.
# Operations | PY

+ list comprehension
+ [further]()

**List comprehension**


In [4]:
l = [["a","b"],["c","d"], ["e","f"]]
print([i for [i, _] in l])
print([i[1] for i in l])
apple_prices = [100, 101, 102, 105]
apple_prices_doubled = [ i*2 for i in apple_prices ]
apple_prices_lowered = [ i - 100 for i in apple_prices ]

['a', 'c', 'e']
['b', 'd', 'f']


-----
Series.
# Useful | PY

A trick when you want to flatten a matrix X of shape (a,b,c,d) to a matrix X_flatten of shape (b ∗∗ c ∗∗ d, a) is to use:

In [16]:
rgb_value = np.array([32, 128, 64])

# 2x2 images
img_1 = np.array([[rgb_value, rgb_value], [rgb_value, rgb_value]])
img_2 = np.array([[rgb_value, rgb_value], [rgb_value, rgb_value]])

# 2 images
train_imgs = np.array([img_1, img_2])

# flattening
train_imgs_flatten = train_imgs.reshape(24, -1).T

print(
    "train_imgs:\n"
    + str(train_imgs)
    
    + "\n\ntrain_imgs_flatten:\n"
    + str(train_imgs_flatten)    
)

(1, 24)
train_imgs:
[[[[ 32 128  64]
   [ 32 128  64]]

  [[ 32 128  64]
   [ 32 128  64]]]


 [[[ 32 128  64]
   [ 32 128  64]]

  [[ 32 128  64]
   [ 32 128  64]]]]

train_imgs_flatten:
[[ 32 128  64  32 128  64  32 128  64  32 128  64  32 128  64  32 128  64
   32 128  64  32 128  64]]


-----
Data Types.Complex Data Types.
# Sets

[mathematical]()

# Sets | PY

Sets are **Set** of **NumPy.Array** or arrays.

**Properties**
+ Unordered
+ Without repetition

Let **S1** such that:

In [54]:
S1 = set([ row[1] for row in s1])

print(
    "S1:\n" + str(S1)
)

S1:
{2, 3}


-----
Data Types.Complex Data Types

# Matrices

[mathematical](http://mathworld.wolfram.com/Matrix.html)

# Matrices | PY

Matrices are specific sort of **Series**.

**Properties**
+ It's elements $e$ are also series (but not recursively)
+ len($e_i$) = len($e_j$), $i \neq j$

Let,

In [19]:
# Scalar values
a = 0
b = 2

# Matrices
A = np.array([[1, 1], [2, 2], [3, 3]])
C = np.array([[2, 2, 2], [3, 3, 3]])
B = [[1, 1], [2, 2], [3, 3]] # classical array

print(
    "Scalar values:\n"
    + "a: " + str(a)
    + "\nb: " + str(b)
)
print("\nA:\n" + str(A) + "\n")
print("C:\n" + str(C) + "\n")
print("B:\n" + str(B) + "\n")

Scalar values:
a: 0
b: 2

A:
[[1 1]
 [2 2]
 [3 3]]

C:
[[2 2 2]
 [3 3 3]]

B:
[[1, 1], [2, 2], [3, 3]]



------

### Matrices.Contents

+ Declaration
+ Number of rows, columns and elements
+ Accessing elements
+ **Remarks**

In [109]:
print("A:\n")
print("shape / dimension: " + str(A.shape))
print("size / #elements: " + str(A.size))
print("len / #rows: " + str(len(A)) + " or " + str(A.shape[0]))
print("#columns: " + str(len(A[0])) + " or " + str(A.shape[1]))

print("\nC:\n")
print("shape / dimension: " + str(C.shape))
print("size / #elements: " + str(C.size))
print("len / #rows: " + str(len(C)) + " or " + str(C.shape[0]))
print("#columns: " + str(len(C[0])) + " or " + str(C.shape[1]))

print("\nB:\n")
print("dimension: (" + str(len(B)) + ", " + str(len(B[0])) + ")") 
print("#elements:" + str(len(B) * len(B[0])))
print("len / #rows: " + str(len(B)))
print("#columns: " + str(len(B[0])))

A:

shape / dimension: (3, 2)
size / #elements: 6
len / #rows: 3 or 3
#columns: 2 or 2

C:

shape / dimension: (2, 3)
size / #elements: 6
len / #rows: 2 or 2
#columns: 3 or 3

B:

dimension: (3, 2)
#elements:6
len / #rows: 3
#columns: 2


### Matrices.Contents.Remarks:
Remarks on the behaviour of **size** and **len**:

In [57]:
print(
    "#elements for [[1, 2], [3, 4]]: " + str(np.array([[1, 2], [3, 4]]).size)
    + "\n#elements for [1, 2, 3, 4]: " + str(np.array([[1, 2], [3, 4]]).size)
    
    + "\n\n#rows for [1, 2, 3]: " + str(len([1, 2, 3]))
    + "\n#rows for [[1, 2, 3]]: " + str(len([[1, 2, 3]]))
    
    + "\n\nno columns for [1, 2, 3]\n"
    + "#columns  for [[1, 2, 3]]: " + str(len([[1, 2, 3]][0])) + "\n"
)

#elements for [[1, 2], [3, 4]]: 4
#elements for [1, 2, 3, 4]: 4

#rows for [1, 2, 3]: 3
#rows for [[1, 2, 3]]: 1

no columns for [1, 2, 3]
#columns  for [[1, 2, 3]]: 3



------
Matrice.

# Operations

+ Operations
    + Transpose
    + Inverse | [py](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html)
    + Sum
    + Product
    + Other
        + Reshape | [py](https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html)
        + **Broadcasting** | [py](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html)
        + Matrix Manipulation
+ Remarks
    + Rank 1 matrices

# Transpose | PY

In [70]:
print("Transpose, A^T:\n" + str(A.transpose()) + "\nor\n" + str(A.T))

Transpose, A^T:
[[1 2 3]
 [1 2 3]]
or
[[1 2 3]
 [1 2 3]]


# Addition | PY

In [24]:
print("\nSum, A + A:\n" + str(A + A) + "\n")


Sum, A + A:
[[2 2]
 [4 4]
 [6 6]]



# Addition* | PY

+ Matrix Addition*
$$(R, C) + (1, 1) \longrightarrow (R, C)\tag{1}$$
$$(R, C) + (R, 1) \longrightarrow (R, C)\tag{2}$$
$$(R, C) + (R, C) \longrightarrow (R, C)\tag{3}$$

In [25]:
A = np.array([[1, 2, 3], [1, 2, 3]])

B = np.array([[1], [1]])

C = np.array([1])

print(
    "Addition*, A + B:\n"
    + str(A + B)
    
    + "\n\nAddition*, A + C:\n"
    + str(A + C)
)

Addition*, A + B:
[[2 3 4]
 [2 3 4]]

Addition*, A + C:
[[2 3 4]
 [2 3 4]]


# Multiplication

+ Inner Product
+ Outer Product
+ Elementwise Product
+ Scalar Product

# Multiplication | PY

In [72]:
print("\nInner product, AC:\n" + str(np.dot(A, C)) + "\n")

print("\nOuter product, A o C:\n" + str(np.outer(A, C)) + "\n")

print("\nScalar product, A o a:\n" + str(np.dot(A, a)) + "\n" + "or:\n" + str(A * a))



Inner product, AC:
[[ 5  5  5]
 [10 10 10]
 [15 15 15]]


Outer product, A o C:
[[2 2 2 3 3 3]
 [2 2 2 3 3 3]
 [4 4 4 6 6 6]
 [4 4 4 6 6 6]
 [6 6 6 9 9 9]
 [6 6 6 9 9 9]]


Scalar product, A o a:
[[0 0]
 [0 0]
 [0 0]]
or:
[[0 0]
 [0 0]
 [0 0]]


# Division | PY

+ Scalar division
    + (R, C) / a $\longrightarrow$ (R, C)
+ Matrix division
    + (R, C) / (1, 1) $\longrightarrow$ (1, 1)
    + (R, C) / (1, C) $\longrightarrow$ (R, C)
    + (R, C) / (R, C) $\longrightarrow$ (R, C)
    

In [148]:
a = 0.5
la = [a, a]
A = np.array([[2, 2], [2, 2], [2, 2]]) # shape (3,2)
B = np.array(la)

print(
    "Scalar division, A / a:\n"
    + str(A / a)
    
    + "\n\nMatrix division, A / B:\n"
    + str(A / B)
)

Scalar division, A / a:
[[4. 4.]
 [4. 4.]
 [4. 4.]]

Matrix division, A / B:
[[4. 4.]
 [4. 4.]
 [4. 4.]]


# Multiplication* | PY

+ Matrix multiplication*
    + (R, C) * (1, 1) $\longrightarrow$ (R, C)
    + (R, C) * (1, C) $\longrightarrow$ (R, C)
    + (R, C) * (R, C) $\longrightarrow$ (R, C)

In [162]:
a = 0.5
la = [a, a]
A = np.array([[2, 2], [2, 2], [2, 2]]) # shape (3,2)
B = np.array(la)

print(    
    "Matrix multiplication, A * B:\n"
    + str(A * la)
)

Matrix multiplication, A * B:
[[1. 1.]
 [1. 1.]
 [1. 1.]]


# Reshape | PY

In [59]:
print(
    "Reshaping A to A.size rows and 1 column:\n" 
    + str(A.reshape(A.size, 1))
    
    + "\nReshaping C to 1 row and C.size columns:\n"
    + str(C.reshape(1, C.size))
)

Reshaping A to A.size rows and 1 column:
[[1]
 [1]
 [2]
 [2]
 [3]
 [3]]
Reshaping C to 1 row and C.size columns:
[[2 2 2 3 3 3]]


### Matrices.Contents.Operations.Other.Broadcasting | py

### Matrices.Contents.Operations.Other.Matrix Manipulation | py

In [60]:
print(
    "Sum all A rows (collapse to single row):\n"
    + str(A.sum(axis = 0))
    + "\npreferably:\n"
    + str(A.sum(axis = 0).reshape(1, len(A[0])))
    
    + "\n\nSum all A columns (collapse to single column):\n"
    + str(A.sum(axis = 1))
    + "\npreferably:\n"
    + str(A.sum(axis = 1).reshape(len(A), 1))
)

Sum all A rows (collapse to single row):
[6 6]
preferably:
[[6 6]]

Sum all A columns (collapse to single column):
[2 4 6]
preferably:
[[2]
 [4]
 [6]]


### Matrices.Contents.Remarks.Rank 1 Matrices | py

**shape** returns a **rank 1** list. Reshaped it to a **non-rank 1** matrice. Numerous bugs arrive from rank 1 lists.

In [23]:
A = np.array([[1, 1], [2, 2], [3, 3]])

print(
    "Shape of sum of all A rows (collapse to single row):\n"
    + str(A.sum(axis = 0).shape)
    
    + "\n\nShape of reshaped sum of all A rows (collapse to single row):\n"
    + str(A.sum(axis = 0).reshape(1, len(A[0])).shape)
)

Shape of sum of all A rows (collapse to single row):
(2,)

Shape of reshaped sum of all A rows (collapse to single row):
(1, 2)


# Primitive Operators

Arithmetic python scala

Logical python scala

-----

# Local File System Access

In [62]:
import os
os.listdir('..')

['advanced_analytics', 'deep_learning', 'machine_learning']

-----
# Method Definition

In [63]:
def f1(a1, a2):
    return a1, a2

def f2(a1):
    return f1(a, a + a)[1]

In [64]:
print(
    f2(1)
)

0


<a id='data_structures'></a>
[/ Data](#data)

-----
# Data Structures

Data has a data type. A data type has at least one data structure. We'll suppose for now that it has **one and one only** data structure. We can try and generalize that the data structure of a data type $\mathbb{D}$ is **how** elements of $\mathbb{D}$ can be obtained with elements of $\mathbb{D}*$ through operations of $\mathbb{O}$.

<code>"string" = 's' + 't' + 'r' + 'i' + 'n' + 'g' </code>

In [65]:
triple = (1,2,3)
dictio = {'x' : 1, 'y' : 2, 'z' : 3}

print(
    "Triple:\n"
    + str(triple)
    + "\nTriple's elements:\n"
    + (lambda x, y, z : str(x) + " " + str(y) + " " + str(z))(*triple)
    
    + "\n\nDictionary:\n"
    + str(dictio)
    + "\nDictionary's keys:\n"
    + (lambda x, y, z : str(x) + " " + str(y) + " " + str(z))(*dictio)
    + "\nDictionary's values:\n"
    + (lambda x, y, z : str(x) + " " + str(y) + " " + str(z))(**dictio)
)

Triple:
(1, 2, 3)
Triple's elements:
1 2 3

Dictionary:
{'x': 1, 'y': 2, 'z': 3}
Dictionary's keys:
x y z
Dictionary's values:
1 2 3


-----

# Function Definition

Lambda functions can't use regular python statements and always include an implicit return statement.

In [66]:
f3 = lambda x, y: (lambda x : 2 * x)(f2(x + y)) # Non-anonymous and anonymous lambda expressions.

In [47]:
print(
    f3(1,1)
)

0


### Method Definition.Remarks

In [48]:
import numpy as np
import time

In [49]:
t0 = time.time()

a = np.random.rand(1000000000)
b = np.random.rand(1000000000)

t1 = time.time()

print(t1 - t0)

KeyboardInterrupt: 

In [ ]:
t0 = time.time()

np.dot(a,b) # transpose and multiply

t1 = time.time()

In [ ]:
tf = t1 - t0
print("time spent on vectorization: " + str(tf))

In [ ]:
t0 = time.time()

acc = 0
for i in range(1000000000):
    acc += a[i] * b[i]
    
t1 = time.time()

In [ ]:
print("Time spent in non-vectorization" + str(t1 - t0))

# Broadcasting

-----

In [ ]:

arr = np.array(
    [[56.0, 0.0, 4.4, 68.0]
    , [1.2, 104.0, 52.0, 8.0]
    , [1.8, 135.0, 99.0, 0.9]]
)

calories = arr.sum(axis=0)



In [ ]:
print( 100 * arr / calories.reshape(1, 4) )

### Don't use RANK1 arrays

In [ ]:
# A RANK1 array, neither a ROW vector, nor a COLUMN vector
arr = np.random.randn(5)
arr

In [ ]:
arr.shape

In [ ]:
arr.T

In [ ]:
arr = np.array(
    [[56.0, 0.0, 4.4, 68.0]
    , [1.2, 104.0, 52.0, 8.0]
    , [1.8, 135.0, 99.0, 0.9]]
)

In [ ]:
arr.shape

In [ ]:
arr = np.random.randn(5,1)
arr

In [ ]:
arr.shape

In [ ]:
arr.T

-----
Computer Programming Language
.Properties
# .Readability

Readability is a property of computer applications with direct implications in properties such as **Scalability** and **Maintenance**. Readability is enforced by [good practices](https://code.tutsplus.com/tutorials/top-15-best-practices-for-writing-super-readable-code--net-8118).

Properties such as **Application Structure** also influence properties such as **Scalability** and **Maintenance**.

-----
Computer Programming Language
.Properties
# .Mutability and Immutability

Mutability is **change that does not affect the identity**. Immutability is **equivalence between state and identity**.

-----
Computer Programming Language
.Properties
# .Substitution Model

The **substitution model** is formalized in the $\lambda$-calculus (a foundation for functional programming). Every expression computes to a value. This model can express every algorithm, being equivalent to a **Turing Machine**.

Expressions with **side-effects** cannot be represented by the $\lambda$-calculus.</p>
**Example:**
```java
c = 1
System.out.println(c++);
System.out.println(c);
```

**Output**   

1 </p>
2

Do all expressions reduce to values in the SModel? No.</p>
**Example:**

```scala    
def loop: Int = loop
loop
```

-----
Computer Programming Language.Properties.
# Evaluation strategies: Call-by-value and Call-by-name

**Call-by-value, CBV**:

    1    sumOfSquares(3, 2 + 2)
    2    sumOfSquares(3, 4)
    3    square(3) + square(4)
    4    3 * 3 + square(4)
    5    3 * 3 + 4 * 4
    6    9 + 4 * 4
    7    9 + 16
    8    25
    
**Advantages**: Evaluates a function argument only once (Call-by-name, steps 5-6: performs *2 + 2* twice). Usually exponentially more efficient than CBN.
    
**Call-by-name, CBN**:

    1    sumOfSquares(3, 2 + 2)
    2    square(3) + square(2 + 2)
    3    3 * 3 + square(2 + 2)
    4    9 + square(2 + 2)
    5    9 + (2 + 2) + (2 + 2) 
    6    9 + 4 + (2 + 2)
    7    9 + 4 * 4
    8    9 + 16
    9    25

**Advantages**: A function argument is not evaluated if it is not used in the evaluation. 

Both strategies **evaluate an expression to a value** *iff*: 
+ reduced expressions consist only of *pure functions* and 
+ all evaluations terminate.

**Properties**:
+ Evaluation **terminates** $\Longleftrightarrow$ Reduced expressions consist only of *pure functions* $\bigwedge$ all evaluations terminate
+ CBV terminates $\Longrightarrow$ CBN terminates

Example:

```scala
def f(x: Int, y: Int) : Int = x
def g(x: Int, y: => Int) : Int = x
```

Call-by-value, CBV:  
    
    1    f(1, loop)
    2    f(1, loop)
    3    ...
    4    f(1, loop)
    5    ...

Call-by-name, CBN:

    1    f(1, loop)
    2    1
    
Scala uses **CBV** and **CBN** whenever the argument as the tokens **=>**. Example:

    1    f(1, loop)
    2    f(1, loop)
    3    ...
    4    f(1, loop)
    5    ...
    
    1    g(1, loop)
    2    1
    

-----
Computer Programming Language.Properties.
# Call-by-value and Call-by-reference

-----
Computer Programming Language.Properties.
# Conditional Expressions

-----
# Algorithms

Algorithms are a finite series of well-defined steps to reduce an expression to a value. The expression is reasoning of a solution to a problem, the value is the solution for the problem.

-----
Algorithms.

# Newton's Method

Newton's algorithm for finding root solutions for real valued functions.

## Implementations

[Mathematical](https://en.wikipedia.org/wiki/Newton%27s_method)

**Scala**:
```scala
def sqrt(root: Double): Double = {

  def inRadius(guess: Double) : Boolean = abs(guess * guess - root) / root < 0.0001

  def approach(guess: Double): Double = ((root / guess) + guess) / 2

  def sqrNewton(guess: Double) : Double =
    if (inRadius(guess)) guess
    else sqrNewton(approach(guess))

  // the last element defines the value
  sqrNewton(1.0)

} + 0
```

    
**Disadvantages**:
For *r* $\in [0, 1]$, (*guess* \* *guess*) $\longrightarrow$ 0 $\Longrightarrow$ (*guess* \* *guess* - *r*) $\longrightarrow$ *r* $\geq$ *radius*

For very large *r*, there will be **overflow**.

Therefore the *inRadius* test is made relatively to *root*

-----
Algorithms.

# Euclid's GCD

## Implementations

[Mathematical](https://en.wikipedia.org/wiki/Newton%27s_method)

**Scala**:
```scala
def factorial (x: Double): Double = {
  def rec (x: Double, acc: Double): Double =
    if (x <= 0) acc
    else rec(x - 1, acc * x)
  rec(x, 1.0)
}
```

    
**Disadvantages**:

-----
Algorithms.

# Newton's Binomium

-----
Algorithms.

# Factorial

## Implementations

[Mathematical]()

**Scala**:
```scala
def sqrt(root: Double): Double = {

  def inRadius(guess: Double) : Boolean = abs(guess * guess - root) / root < 0.0001

  def approach(guess: Double): Double = ((root / guess) + guess) / 2

  def sqrNewton(guess: Double) : Double =
    if (inRadius(guess)) guess
    else sqrNewton(approach(guess))

  // the last element defines the value
  sqrNewton(1.0)

} + 0
```

-----
Computer Programming Language.Properties
# Recursion and Tail Recursion

Recursion uses a method's **stack frame** (limited up to 1000 in the JVM). Whenever a method is deeply recursive, use **Tail Recursion**: reuse the stack frame of the method.
```scala
import scala.annotation.tailrec
@tailrec
def gcd(a: Int, b: Int): Int = if (b == 0) a else gcd(b, a % b)
```

<a id='ai'></a>
[/](#root)

-----
# Artificial Intelligence

AI are complex algorithms one can say to be *intelligent*.

<a id='machine_learning'></a>
[/ Artificial Intelligence](#ai)

-----

# Machine Learning

Machine learning is a field of AI where **algorithms** are developed by the program itself, rather than by the programmer.

<a id='deep_learning'></a>
[/ Artificial Intelligence / Machine Learning](#machine_learning)

-----

# Deep Learning

Key terms: <font color="blue">dataset, training dataset, test dataset, neural network, activation function</font>

Deep learning is a field of machine learning. It extrapolates information from data by **training the algorithm** from a **training dataset**. For small training datasets, traditional learning algorithms were sufficient. For large training datasets, neural networks excelled. Neural networks evolved by innovation in the **activation function** (ex.: switching from a $\sigma$-oid function to a *RELU*-function)

## Contents

+ Neural Networks [$\rightleftharpoons$](#neural_networks)
    + Recurrent Neural Networks
    + Standard Neural Networks
    + Convolutional Neural Networks
+ Supervised Learning [$\rightleftharpoons$](#deep_learning)
+ Binary Classification [$\rightleftharpoons$](#deep_learning)
+ Logistic Regression [$\rightleftharpoons$](#deep_learning)
+ Cost and Loss Functions [$\rightleftharpoons$](#deep_learning)
+ Gradient Descent [$\rightleftharpoons$](#deep_learning)
+ Computation Graph [$\rightleftharpoons$](#deep_learning)
+ Logistic Regression and Gradient Descent [$\rightleftharpoons$](#deep_learning)
+ Vectorization [$\rightleftharpoons$](#deep_learning)

<a id='neural_networks'></a>
[/ Artificial Intelligence / Machine Learning / Deep Learning](#machine_learning)

-----

# Neural Networks

An **oriented graph** whose nodes are **functions** $f$, whose input lines are **input values to** $f$, and whose output lines are **output values** to other nodes/functions. There are:

+ Recurrent Neural Networks
+ Standard Neural Networks
+ Convolutional Neural Networks

<a id='binary_classification'></a>
[/ Artificial Intelligence / Machine Learning / Deep Learning](#machine_learning)

-----

# Binary Classification

Binary Classification is an **application** $BC$ mapping the encoding of an image to a classification of either 1 or 0. *E.g.:* Is it a cat? Is it not a cat?

$$BC : \mathbb{N}^{mxnx3} \longrightarrow \{0, 1\} \tag{1}$$

If $m=n$, $X \in  \mathbb{N}^{n_x}$, being $x$ the square image. Given that the **training set** consists of $M$ training examples, X_i, $i \leq M$ are the respective encodings for every training image $x^{(i)}$. Equivalently, binary classification is the **set** $BC$:

$$ BC = \{(x^{(i)}, y^{(i)}) : i \leq M\}\tag{2}$$

With $y^{(i)}$, the classification of $x^{(i)}$. The encodings of $x^{(i)}$ are assembled in the **matrix** $X$:

$$X \in M_{(mxnx3)xM} (\mathbb{N}) \tag{3}$$

Where $x^{(i)}$ coordinates are distributed along the column $i$ of X. The classifications are assembled in the **vector** $Y$:

$$ Y = (x^{(1)}, ..., x^{(m)}) \tag{4}$$

## Continues

+ Logistic Regression [$\rightleftharpoons$](#logistic_regression)
+ Cost and Loss Functions [$\rightleftharpoons$](#cost_loss_function)
+ Gradient Descent [$\rightleftharpoons$](#gradient_descent)


<a id='logistic_regression'></a>
[/ Artificial Intelligence / Machine Learning / Deep Learning / Binary Classification](#machine_learning)

-----

# Logistic Regression

Logistic regression is a **machine learning parametrized algorithm** designed to **increase** the probability of a correct classification of $y^{(i)}$: $\hat{y}^{(i)} \longrightarrow 1$.

$$ \hat{y}^{(i)} = P( y^{(i)} = 1 \:\mid\: x^{(i)} ) \in [0, 1] \tag{1}$$

The estimates of the classifications are assembled in the **vector** $\hat{Y}$:

$$ \hat{Y} = (\hat{y}^{(1)}, ..., \hat{y}^{(m)}) \tag{2}$$

Obtained as: 

$$ \hat{Y} = \sigma(W^TX + b) \tag{3}$$

Parameters to the algorithm are $W \in \mathbb{R}^{n_x}$ and $b \in \mathbb{R}$. The algorithm works by **iteratively improving / learning / training** the values for $W, b$ such that $\hat{y}^{(i)} \simeq y^{(i)}$.

$\sigma$ must be a function such that:<font color="red">? WHY ?</font>
$$\lim_{x \to +\infty} \sigma(x) \longrightarrow 1\tag{4}$$
$$\lim_{x \to -\infty} \sigma(x) \longrightarrow 0\tag{5}$$

And so the definition can be that of:

$$\sigma(x) = \frac{1}{1 + e^{-x}}\tag{6}$$

[wolphram](https://www.wolframalpha.com/input/?i=1+%2F+(1+%2B+e%5E(-x)

<font color="blue">How does $\sigma$ satisfy conditions 4 and 5?</font>

<a id='cost_loss_functions'></a>
[/ Artificial Intelligence / Machine Learning / Deep Learning / Binary Classification](#machine_learning)

-----

# Cost and Loss Functions

Given that the algorithm performs **iteratively** to **improve / learn / train**, each iteration evaluates the fitness or the loss of $\hat{Y}$ in relation to $Y$, $\mathcal{L}(\hat{y}, y)$. $\mathcal{L}$  must be a function such that:

$$ y = 1 \:then: \hat{y} \longrightarrow 1 \Longrightarrow \mathcal{L}(\hat{y}, y) \longrightarrow 0\tag{1.1}$$
$$ y = 1 \:then: \hat{y} \longrightarrow 0 \Longrightarrow \mathcal{L}(\hat{y}, y) \longrightarrow +\infty\tag{1.2}$$
$$ y = 0 \:then: \hat{y} \longrightarrow 1 \Longrightarrow \mathcal{L}(\hat{y}, y) \longrightarrow 0\tag{2.1}$$
$$ y = 0 \:then: \hat{y} \longrightarrow 0 \Longrightarrow \mathcal{L}(\hat{y}, y) \longrightarrow +\infty\tag{2.2}$$
$$\mathcal{L} \:be \:convex\tag{3}$$

Convex functions [$\rightleftharpoons$](#functions_properties) ensure an **absolute minimum**, $i.e.$, an optimal solution. And so the definition can be that of:

$$\mathcal{L}(\hat{y}, y) = -(ylog(\hat{y}) + (1 - y)log(1 - \hat{y}))\tag{6}$$

<font color="blue">How does $\mathcal{L}$ satisfy conditions 1.* to 3?</font>

The cost function $\mathcal{J}(W, b)$ can simply be the mean of the loss over the training set:

$$\mathcal{J}(W, b) = \frac{1}{M}\sum_{1}^{M}\mathcal{L}(\hat{y}^{(i)}, y^{(i)}) $$

Learning is thus a matter of minimizing $\mathcal{J}$.

<a id='gradient_descent'></a>
[/ Artificial Intelligence / Machine Learning / Deep Learning / Binary Classification](#machine_learning)

-----

# Gradient Descent
